# this runs my Docker located in  /docker
version: "3.9"

volumes:
  pg-data:

services:
  proxy:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    links:
      - app
  app:
    ports:
      - 4000
    build:
      context: ./docker
      dockerfile: Dockerfile.local
    env_file:
      - .env-docker
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-bullseye
    env_file:
      - .env-docker
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/dbinit.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
